import type {Metadata} from "next";
import {Dosis, Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import Navbar, {NavbarProps} from "@/components/navbar";
import {Providers} from "@/lib/providers/theme-provider";
import {LucideMail} from "lucide-react";
import {SiGithub, SiLinkedin} from "react-icons/si";
import {themes} from "@/lib/themes";

const fontSans = Dosis({
    variable: "--font-sans",
    subsets: ["latin"],
});

const fontMono = Ubuntu_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
    weight: "400"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const navbarProps: NavbarProps = {
    themes: themes,
    title: '<Portfolio/>',
    link: '#',
    navbarItems: [
        {
            id: 'articles-link',
            title: 'Articles',
            link: '#',
        },
        {
            id: 'latest-link',
            title: 'Latest',
            link: '#'
        },
        {
            id: 'more-link',
            title: 'More',
            link: '#',
            subItems: [
                {
                    id: 'gallery-link',
                    title: 'Gallery',
                    link: '#',
                },
                {
                    id: 'news-link',
                    title: 'News',
                    link: '#'
                }
            ]
        }
    ],
    navbarButtons: [
        {
            id: 'linkedin-btn',
            // title: 'LinkedIn',
            link: '#',
            icon: <SiLinkedin />
        },
        {
            id: 'github-btn',
            // title: 'Github',
            link: '#',
            icon: <SiGithub />
        },
        {
            id: 'contact-btn',
            // title: 'Contact',
            link: '#',
            icon: <LucideMail />
        }
    ],
}

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en"  suppressHydrationWarning>
        <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <Providers>
        <Navbar
            themes={navbarProps.themes}
            navbarItems={navbarProps.navbarItems}
            navbarButtons={navbarProps.navbarButtons}
            title={navbarProps.title}
            link={navbarProps.link}></Navbar>
        {children}
        </Providers>
        </body>
        </html>
    );
};
